modules:
  default:
    enable:
      - tcl
    tcl:
      projections:
        all: '{compiler.name}-{compiler.version}/{name}:{version}-{compiler.name}'
        +mpi: '{compiler.name}-{compiler.version}/{name}:{version}-{^mpi.name}-{compiler.name}'
        +mpi+cuda: '{compiler.name}-{compiler.version}/{name}:{version}-{^mpi.name}-{+cuda}'
      hash_length: 0
      all:
        conflict:
          - '{name}'
        environment:
          set:
            '{name}_ROOT_DIR': '{prefix}'
      mpich:
        environment:
          set:
            'UCX_NET_DEVICES': 'mlx5_0:1'
      #^python:
      #  autoload: 'direct'
      include: ['intel-oneapi-mkl','boost','hypre','superlu-dist','petsc', 'slepc', 'adios', 'hypre','hdf5','fftw','openblas','netlib-lapack','netlib-scalapack'] 
      exclude: ['%intel', '%gcc']
