packages:
  mesa:
    variants: +opengl +glx swr=skx
  llvm:
    variants: +cuda cuda_arch=70
  slurm:
    paths:
      slurm@19.05.2: /nopt/slurm/current
    buildable: False
  cuda:
    version: [10.1.243]
    paths:
      cuda@10.0.130: /nopt/nrel/apps/cuda/10.0.130
      cuda@9.2.88: /nopt/nrel/apps/cuda/9.2.88
    #buildable: False
  openmpi:
    variants: +pmi +cuda fabrics=ucx schedulers=slurm legacylaunchers=true
  mpich:
    variants: netmod=ucx device=ch4 +slurm +hydra
  #hwloc:
  #  variants: ~cuda ~nvml ~gl
  fftw:
    variants: +mpi+fma simd=avx512
  libfabric:
    variants: fabrics=verbs
  pgi:
    variants: +nvidia
