packages:
  mesa:
    variants: +opengl +glx swr=skx
  llvm:
    variants: +cuda cuda_arch=70
  slurm:
    paths:
      slurm@19.05.2: /nopt/slurm/current
    buildable: False
  cuda:
    version: [10.1.243]
  openmpi:
    variants: +pmi +cuda fabrics=ucx schedulers=slurm legacylaunchers=true
  mpich:
    variants: netmod=ucx device=ch4 +slurm +hydra
  py-horovod:
    variants: tensor_ops=mpi frameworks=pytorch,tensorflow
  py-tensorflow:
    variants: +cuda cuda_arch=70 +nccl
  py-torch:
    variants: +cuda cuda_arch=70 +cudnn +nccl
  fftw:
    variants: +mpi+fma simd=avx512
  libfabric:
    variants: fabrics=verbs
  pgi:
    variants: +nvidia
