packages:
  mesa:
    variants: +opengl +glx swr=skx
  llvm:
    variants: +omp_debug+omp_tsan+cuda cuda_arch=70 build_type=Release
  slurm:
    paths:
      slurm@19.05.2: /nopt/slurm/current
    buildable: False
  hwloc:
    variants: +cuda
  cuda:
    version: [10.1.243]
  cudnn:
    version: [7.6.5.32-10.1-linux-x64]
  openmpi:
    variants: +pmi +cuda fabrics=ucx schedulers=slurm legacylaunchers=true
  mpich:
    variants: netmod=ucx device=ch4 +slurm +hydra
  py-horovod:
    variants: tensor_ops=mpi frameworks=pytorch,tensorflow
  py-tensorflow:
    variants: +cuda cuda_arch=70 +nccl
  py-torch:
    variants: +cuda cuda_arch=70 +cudnn +nccl
  fftw:
    variants: +mpi+fma simd=avx512
  libfabric:
    variants: fabrics=verbs
  pgi:
    variants: +nvidia
  ucx:
    variants: +optimizations+gdrcopy
    version: [1.8.1]
