modules:
  enable:
    - tcl

  tcl:
    naming_scheme: '${COMPILERNAME}-${COMPILERVER}/${PACKAGE}/${VERSION}'
    hash_length: 0
    all:
      suffixes:
        #'boost+mpi': 'mpi'
        'yaml-cpp~shared': 'static'
        'amrvis dims=3': '3d'
        'amrvis dims=2': '2d'
      conflict:
        - '${PACKAGE}'
      environment:
        set:
          '${PACKAGE}_ROOT_DIR': '${PREFIX}'
    #blacklist: ['pcre']
