packages:
  mesa:
    variants: +opengl +glx swr=skx
  llvm:
    variants: +omp_debug+omp_tsan+cuda cuda_arch=70 build_type=Release
  slurm:
    buildable: false
    externals:
    - spec: slurm@21-08-8-2
      prefix: /nopt/slurm/21.08.8-2/
  hwloc:
    variants: +cuda
  hypre:
    version: [develop]
    variants: ~superlu-dist
  cuda:
    externals:
    - spec: cuda@11.7.0
      prefix: /nopt/nrel/apps/base/warsalan/csso_08_22/mpi/08-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-10.1.0/openmpi-4.1.4-wy377nzxl7jr2eroiq5mn5db7lpmlcfq
    buildable: false
  cudnn:
    version: [7.6.5.32-10.1-linux-x64]
  openmpi:
    buildable: false
    externals:
    - spec: openmpi@4.1.4%gcc@10.1.0 
      prefix: /nopt/nrel/apps/base/warsalan/csso_08_22/mpi/08-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-10.1.0/openmpi-4.1.4-wy377nzxl7jr2eroiq5mn5db7lpmlcfq
    - spec: openmpi@4.1.4%intel@2021.6.0 
      prefix: /nopt/nrel/apps/base/warsalan/csso_08_22/mpi/08-22/spack/opt/spack/linux-centos7-skylake_avx512/intel-2021.6.0/openmpi-4.1.4-qejlxesh6vldlkculopkwh6ym2ramj66
  mpich:
    variants: netmod=ucx device=ch4 +slurm +hydra
  py-horovod:
    variants: tensor_ops=mpi frameworks=pytorch,tensorflow
  py-tensorflow:
    variants: +cuda cuda_arch=70 +mpi +nccl
  py-torch:
    variants: +cuda cuda_arch=70 +cudnn +nccl
  fftw:
    variants: +mpi+fma simd=avx512
  libfabric:
    variants: fabrics=verbs
  pgi:
    variants: +nvidia
  ucx:
    variants: +optimizations+gdrcopy
    version: [1.13.0]
  mpt:
    version: [2.22]
    buildable: false
    externals:
    - spec: mpt@2.22
      prefix: /opt/hpe/hpc/mpt/mpt-2.22
  all:
    compiler: [gcc%10.1.0, intel, clang]
    variants: build_type=Release +mpi
    providers:
      mpi: [openmpi]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
      gl: [osmesa+opengl]
      glx: [osmesa+glx]
