spack:
  specs:
  - osu-micro-benchmarks
  - py-numpy
  - py-matplotlib
  - py-pandas
  - py-nose
  - py-autopep8
  - py-flake8
  - py-horovod
  - py-jedi
  - py-pip
  - py-pyyaml
  - py-seaborn
  - py-sphinx
  - py-scipy
  - py-tensorflow
  - py-torch
  - py-yapf
  - py-yt
  - percept
  - masa
  - valgrind
  - ascent
  - sensei ^llvm@8.0.0
  - amrvis dims=3
  - amrvis+profiling dims=2
  - paraview ^llvm@8.0.0
  - nalu-wind~catalyst
  - netcdf-fortran
  - sundials
  - nalu-wind~catalyst %intel ^intel-mpi
  - nalu-wind~catalyst %clang
  view: false
