upstreams:
  spack-utilities:
    install_tree: /nopt/nrel/apps/base/warsalan/csso_08_22/utilities/08-22/spack/opt/spack
  spack-compilers: 
    install_tree: /nopt/nrel/apps/base/warsalan/csso_08_22/compilers/08-22/spack/opt/spack
  spack-mpi: 
    install_tree: /nopt/nrel/apps/base/warsalan/csso_08_22/mpi/08-22/spack/opt/spack
