compilers:
- compiler:
    environment: {}
    extra_rpaths:
     - /nopt/nrel/apps/base/warsalan/csso/base/07-22/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-8.4.0-7rhq6vy7l65twtlycf5uojcxhw24fh62/lib64
    modules: []
    operating_system: centos7
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/base/07-22/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-8.4.0-7rhq6vy7l65twtlycf5uojcxhw24fh62/bin/gcc
      cxx: /nopt/nrel/apps/base/warsalan/csso/base/07-22/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-8.4.0-7rhq6vy7l65twtlycf5uojcxhw24fh62/bin/g++
      f77: /nopt/nrel/apps/base/warsalan/csso/base/07-22/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-8.4.0-7rhq6vy7l65twtlycf5uojcxhw24fh62/bin/gfortran
      fc: /nopt/nrel/apps/base/warsalan/csso/base/07-22/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-8.4.0-7rhq6vy7l65twtlycf5uojcxhw24fh62/bin/gfortran
    spec: gcc@8.4.0
    target: x86_64
