modules:
  default:
    enable:
      - tcl
    tcl:
      projections:
        all: '{compiler.name}-{compiler.version}/{name}:{version}'
      hash_length: 0
      all:
        conflict:
          - '{name}'
        environment:
          set:
            '{name}_ROOT_DIR': '{prefix}'
      intel-parallel-studio:
        environment:
          set:
            INTEL_LICENSE_FILE: '28519@license-1.hpc.nrel.gov'
      pgi:
        environment:
          set:
            PGROUPD_LICENSE_FILE: '27001@license-1.hpc.nrel.gov'
      include: ['aocc','arm-forge','nvhpc','cuda', 'gcc', 'go', 'llvm', 'intel-oneapi-compilers', 'pgi']
      exclude: ['%gcc']
