packages:
  mesa:
    variants: +opengl +glx swr=skx
  llvm:
    variants: +omp_debug+omp_tsan+cuda cuda_arch=70 build_type=Release
  slurm:
    buildable: false
    externals:
    - spec: slurm@21-08-8-2
      prefix: /nopt/slurm/21.08.8-2/
  hwloc:
    variants: +cuda
  hypre:
    version: [develop]
    variants: ~superlu-dist
  cudnn:
    version: [7.6.5.32-10.1-linux-x64]
  openmpi:
    variants: +pmi +cuda fabrics=ucx schedulers=slurm legacylaunchers=true ~vt
  mpich:
    variants: netmod=ucx device=ch4 +slurm +hydra
  py-horovod:
    variants: tensor_ops=mpi frameworks=pytorch,tensorflow
  py-tensorflow:
    variants: +cuda cuda_arch=70 +mpi +nccl
  py-torch:
    variants: +cuda cuda_arch=70 +cudnn +nccl
  fftw:
    variants: +mpi+fma simd=avx512
  libfabric:
    variants: fabrics=verbs
  pgi:
    variants: +nvidia
  ucx:
    variants: +optimizations+gdrcopy
    version: [1.13.0]
  mpt:
    version: [2.22]
    buildable: false
    externals:
    - spec: mpt@2.22
      prefix: /opt/hpe/hpc/mpt/mpt-2.22
  all:
    compiler: [gcc, oneapi, clang]
    variants: build_type=Release +mpi
    providers:
      mpi: [mpt]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
      gl: [osmesa+opengl]
      glx: [osmesa+glx]
