packages:
  #findutils:
  #   externals:
  #    - spec: findutils@4.8.0%apple-clang@12.0.0
  #      prefix: /Users/<username>/.brew/Cellar/findutils/4.8.0_1
  all:
    compiler: [apple-clang]
    providers:
      mpi: [openmpi]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
