config:
  install_tree: $spack/opt/spack
  template_dirs:
    - $spack/share/spack/templates
  install_path_scheme: "${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}"
  build_stage:
    - /scratch/$user/.spack/stage
    #- $spack/var/spack/stage
    #- $tempdir/$user/spack-stage
    #- ~/.spack/stage
  source_cache: /scratch/$user/.spack/downloads
  misc_cache: /scratch/$user/.spack/cache
  build_jobs: 16
