packages:
  ascent:
    variants: +python
  catalyst:
    variants: +osmesa~python+python3+essentials+extras+rendering
  emacs:
    variants: +tls
  fftw:
    variants: +fma
  gcc:
    variants: languages=c,c++,fortran,go
  hdf5:
    version: [1.10.7]
    variants: +cxx+hl
  hypre:
    variants: +int64~superlu-dist
  intel-parallel-studio:
    variants: +advisor+inspector+itac+mkl+vtune
  intel-mpi:
    version: [2018.4.274]
  intel-mkl:
    version: [2018.4.274]
  llvm:
    variants: +omp_debug+omp_tsan+python build_type=Release
  nalu-wind:
    variants: +openfast+tioga+hypre+fftw build_type=Release
  netcdf-c:
    version: [4.7.4]
    variants: +parallel-netcdf maxdims=65536 maxvars=524288
  openfast:
    version: [develop]
    variants: +cxx build_type=Release
  paraview:
    variants: +hdf5+python3~python+osmesa build_type=Release
  py-yt:
    variants: ~astropy
  parallel-netcdf:
    version: [1.12.2]
  sensei:
    variants: +catalyst+hdf5+python build_type=Release
  superlu:
    version: [4.3]
  texlive:
    variants: scheme=full
  tioga:
    version: [develop]
  trilinos:
    version: [develop]
    variants: ~adios2~alloptpkgs~amesos+amesos2~anasazi~aztec+belos+boost~cgns~chaco~complex~debug~dtk~epetra~epetraext+exodus+explicit_template_instantiation~float~fortran~fortrilinos+glm+gtest+hdf5~hypre~ifpack+ifpack2~intrepid~intrepid2~isorropia+kokkos~matio~mesquite+metis~minitensor~ml+mpi+muelu~mumps+netcdf~nox~openmp~phalanx~piro+pnetcdf~python~rol~rythmos~sacado+shards~shylu+stk~stratimikos~suite-sparse+superlu~superlu-dist~teko~tempus+teuchos+tpetra~x11~xsdkflags+zlib+zoltan+zoltan2 cxxstd=14 build_type=Release
  visit:
    variants: ~gui+hdf5+python+silo+adios2
  vim:
    variants: +python+huge+cscope
  all:
    compiler: [gcc, intel, clang]
    variants: build_type=Release +mpi
    providers:
      mpi: [openmpi, intel-mpi]
      blas: [netlib-lapack, intel-mkl]
      lapack: [netlib-lapack, intel-mkl]
      gl: [osmesa+opengl]
      glx: [osmesa+glx]

