packages:
  binutils:
    version: [2.34]
  boost:
    version: [1.68.0]
  cmake:
    version: [3.17.3]
  fftw:
    variants: +fma
  gcc:
    variants: languages=c,c++,fortran,go
  hdf5:
    version: [1.10.4]
    variants: +cxx+hl
  hypre:
    version: [2.18.2]
    variants: +int64~superlu-dist
  intel-parallel-studio:
    variants: +advisor+inspector+itac+mkl+mpi+vtune
  libxml2:
    version: [2.9.8]
  llvm:
    variants: +omp_debug+omp_tsan+python
  netcdf-c:
    version: [4.7.3]
    variants: +parallel-netcdf maxdims=65536 maxvars=524288
  openfast:
    version: [develop]
    variants: +cxx
  openmpi:
    version: [4.0.4]
  python:
    version: [3.7.7]
  mpich:
    version: [3.3.2]
  parallel-netcdf:
    version: [1.12.1]
  netlib-lapack:
    version: [3.8.0]
  superlu:
    version: [4.3]
  tioga:
    version: [develop]
  trilinos:
    version: [develop]
    variants: ~python~complex+explicit_template_instantiation~float~fortran~openmp~xsdkflags+boost~cgns+exodus+gtest+hdf5~hypre~metis~mumps+pnetcdf~suite-sparse~superlu-dist+superlu~x11+zlib~alloptpkgs~amesos+amesos2~anasazi~aztec+belos~epetra~epetraext~ifpack+ifpack2~intrepid~intrepid2~isorropia+kokkos~ml~minitensor+muelu~nox~piro~phalanx~rol~rythmos~sacado~shylu+stk+shards~teko~tempus+teuchos+tpetra+zoltan+zoltan2~dtk~fortrilinos build_type=Release
  all:
    compiler: [apple-clang, gcc@9.3.0, intel, clang]
    variants: build_type=Release +mpi
    providers:
      mpi: [open-mpi, intel-mpi]
      blas: [netlib-lapack, intel-mkl]
      lapack: [netlib-lapack, intel-mkl]

