compilers:
- compiler:
    spec: gcc@4.8.5
    paths:
      cc: /usr/bin/gcc
      cxx: null
      f77: null
      fc: null
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@7.5.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-7.5.0-6fxgxnt2qxupapvr3ya2rahrwxjbasu6/bin/gcc
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-7.5.0-6fxgxnt2qxupapvr3ya2rahrwxjbasu6/bin/g++
      f77: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-7.5.0-6fxgxnt2qxupapvr3ya2rahrwxjbasu6/bin/gfortran
      fc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-7.5.0-6fxgxnt2qxupapvr3ya2rahrwxjbasu6/bin/gfortran
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@8.5.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-8.5.0-vt3it6kreyj6knbtohazcd3qnacnks6d/bin/gcc
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-8.5.0-vt3it6kreyj6knbtohazcd3qnacnks6d/bin/g++
      f77: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-8.5.0-vt3it6kreyj6knbtohazcd3qnacnks6d/bin/gfortran
      fc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-8.5.0-vt3it6kreyj6knbtohazcd3qnacnks6d/bin/gfortran
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.4.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-9.4.0-4t5c4jaj4vmpl73hwwxmqbscbdzjcq3s/bin/gcc
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-9.4.0-4t5c4jaj4vmpl73hwwxmqbscbdzjcq3s/bin/g++
      f77: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-9.4.0-4t5c4jaj4vmpl73hwwxmqbscbdzjcq3s/bin/gfortran
      fc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-9.4.0-4t5c4jaj4vmpl73hwwxmqbscbdzjcq3s/bin/gfortran
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@10.3.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-10.3.0-hkcoh5yowngw3ht6y7q5mauuqt7zs2dv/bin/gcc
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-10.3.0-hkcoh5yowngw3ht6y7q5mauuqt7zs2dv/bin/g++
      f77: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-10.3.0-hkcoh5yowngw3ht6y7q5mauuqt7zs2dv/bin/gfortran
      fc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-10.3.0-hkcoh5yowngw3ht6y7q5mauuqt7zs2dv/bin/gfortran
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-11.2.0-q6o22bumnwourgtmlqc7zqzeokuwxx3j/bin/gcc
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-11.2.0-q6o22bumnwourgtmlqc7zqzeokuwxx3j/bin/g++
      f77: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-11.2.0-q6o22bumnwourgtmlqc7zqzeokuwxx3j/bin/gfortran
      fc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/gcc-11.2.0-q6o22bumnwourgtmlqc7zqzeokuwxx3j/bin/gfortran
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@10.0.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/llvm-10.0.0-rm2g72jvq65ibcmxdo2aimrn7h4m4v2i/bin/clang
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/llvm-10.0.0-rm2g72jvq65ibcmxdo2aimrn7h4m4v2i/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@11.1.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/llvm-11.1.0-ffrg4bqsnana5bqwvg35k4lwrhqqwk4d/bin/clang
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/llvm-11.1.0-ffrg4bqsnana5bqwvg35k4lwrhqqwk4d/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@12.0.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/llvm-12.0.0-aq3bp4nm4xyahdhps2bntgn3nq5s6vrg/bin/clang
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/llvm-12.0.0-aq3bp4nm4xyahdhps2bntgn3nq5s6vrg/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@13.0.1
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/llvm-13.0.1-s5z4jfjzcmgbsnxugiwul6i4bxqvhlcc/bin/clang
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/llvm-13.0.1-s5z4jfjzcmgbsnxugiwul6i4bxqvhlcc/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@14.0.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/llvm-14.0.0-fxjyucdb6zel3d7fumnf5aanhqo6z5j7/bin/clang
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/llvm-14.0.0-fxjyucdb6zel3d7fumnf5aanhqo6z5j7/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@19.0.5.281
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-parallel-studio-cluster.2019.5-lg7kajzzqnaa433qehdbl545k2cc3t6k/compilers_and_libraries_2019.5.281/linux/bin/intel64/icc
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-parallel-studio-cluster.2019.5-lg7kajzzqnaa433qehdbl545k2cc3t6k/compilers_and_libraries_2019.5.281/linux/bin/intel64/icpc
      f77: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-parallel-studio-cluster.2019.5-lg7kajzzqnaa433qehdbl545k2cc3t6k/compilers_and_libraries_2019.5.281/linux/bin/intel64/ifort
      fc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-parallel-studio-cluster.2019.5-lg7kajzzqnaa433qehdbl545k2cc3t6k/compilers_and_libraries_2019.5.281/linux/bin/intel64/ifort
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: dpcpp@2022.1.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/icx
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/dpcpp
      f77: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/ifx
      fc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/ifx
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2021.6.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/intel64/icc
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/intel64/icpc
      f77: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/intel64/ifort
      fc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@2022.1.0
    paths:
      cc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/icx
      cxx: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/icpx
      f77: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/ifx
      fc: /nopt/nrel/apps/base/warsalan/csso/compilers/07-22/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-25biauwuq3vjwvwvrjlnkz4ujw73soh4/compiler/2022.1.0/linux/bin/ifx
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
