packages:
  mesa:
    variants: swr=avx2
  fftw:
    variants: simd=avx2
  py-horovod:
    variants: tensor_ops=mpi frameworks=pytorch,tensorflow
  py-tensorflow:
    variants: ~cuda ~nccl
  py-torch:
    variants: ~cuda ~cudnn ~nccl
