compilers:
- compiler:
    environment: {}
    extra_rpaths:
     - /opt/base/2020-07-06/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-9.3.0-oxjixak2sy5mudydbjatzvj4bpveh5jl/lib64
    modules: []
    operating_system: centos7
    paths:
      cc: /opt/base/2020-07-06/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-9.3.0-oxjixak2sy5mudydbjatzvj4bpveh5jl/bin/gcc
      cxx: /opt/base/2020-07-06/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-9.3.0-oxjixak2sy5mudydbjatzvj4bpveh5jl/bin/g++
      f77: /opt/base/2020-07-06/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-9.3.0-oxjixak2sy5mudydbjatzvj4bpveh5jl/bin/gfortran
      fc: /opt/base/2020-07-06/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-9.3.0-oxjixak2sy5mudydbjatzvj4bpveh5jl/bin/gfortran
    spec: gcc@9.3.0
    target: x86_64
