modules:
  enable:
    - tcl

  tcl:
    naming_scheme: '${COMPILERNAME}-${COMPILERVER}/${PACKAGE}/${VERSION}'
    hash_length: 0
    all:
      conflict:
        - '${PACKAGE}'
      environment:
        set:
          '${PACKAGE}_ROOT_DIR': '${PREFIX}'
    intel-parallel-studio:
      environment:
        set:
          INTEL_LICENSE_FILE: '28519@license-1.hpc.nrel.gov'
    pgi:
      environment:
        set:
          PGROUPD_LICENSE_FILE: '27001@license-1.hpc.nrel.gov'
    whitelist: ['gcc', 'go', 'llvm', 'intel-parallel-studio', 'binutils', 'pgi']
    blacklist: ['%gcc@9.3.0']
