packages:
  mesa:
    variants: +opengl +glx swr=skx
  llvm:
    variants: +omp_debug+omp_tsan+cuda cuda_arch=70 build_type=Release
  hwloc:
    variants: +cuda
  hypre:
    version: [develop]
    variants: ~superlu-dist
  cudnn:
    version: [8.4.0.27-11.6]
  openmpi:
    variants: +pmi +cuda fabrics=verbs schedulers=slurm legacylaunchers=true ~vt
  mpich:
    variants: netmod=ucx device=ch4 +slurm +hydra
  py-horovod:
    variants: tensor_ops=mpi frameworks=pytorch,tensorflow
  py-tensorflow:
    variants: +cuda cuda_arch=70 +mpi +nccl
  py-torch:
    variants: +cuda cuda_arch=70 +cudnn +nccl
  fftw:
    variants: +mpi+fma simd=avx512
  libfabric:
    variants: fabrics=verbs
  pgi:
    variants: +nvidia
  ucx:
    variants: +optimizations+gdrcopy
    version: [1.13.0]
  all:
    compiler: [gcc@12.1.0, intel-oneapi-compilers@22.1.0, clang@14.0.6]
    variants: build_type=Release +mpi
    providers:
      mpi: [mpt,openmpi,intel-mpi]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
      gl: [osmesa+opengl]
      glx: [osmesa+glx]
