spack:
  specs:
  - bc
  - bison
  - bzip2
  - cmake
  - cppcheck
  - curl
  - flexi@2.6.4
  - flex@2.5.39
  - ffmpeg
  - emacs
  - git
  - gdb
  - gnuplot+wx 
  - gnutls
  - htop
  - imagemagick 
  - libxml2
  - likwid
  - ninja
  - mercurial
  - makedepend
  - patch
  - pkg-config
  - python@3.10.5
  - python@2.7.18
  - rsync
  - screen
  - stow
  - strace
  - texinfo
  - texlive 
  - tmux
  - unzip
  - vim
  - wget
  - zsh
  #- global
  #- xterm
  view: false
